"""
MARGEM-REAL-2 — a consulta REAL do conector do ML, contra PostgreSQL real.

`test_ml_comissao_transform.py` mede as regras que não precisam de banco.
Aqui roda-se `ml_connector.QUERY` — a string exata que vai para o Data Mart —
contra um cluster descartável com tabelas sintéticas de mesma forma.

Por que não basta um fake: um duplo devolve o que se mandou, e as coisas que
podem dar errado aqui são todas do banco — a chave do join, o tipo da coluna,
a borda do `date_created::date`, o fan-out de um join 1:N. O diagnóstico do
MARGEM-REAL-1 encontrou exatamente esse tipo de armadilha: um join por
`api.ml_orders.id` devolve zero linha sem erro, e nenhum fake reproduz isso
porque o fake não conhece a diferença entre `id` e `order_id`.

Sem PostgreSQL (`PMA_TEST_PG_BIN`, `.local/postgres16` ou no PATH), SKIP.
"""
from __future__ import annotations

import pytest
from sqlalchemy import create_engine, text

from pipelines.connectors.mercadolivre import connector as ml_connector
from pipelines.tests.postgres_descartavel import (
    MOTIVO_SEM_POSTGRES,
    cluster_descartavel,
    postgres_disponivel,
)

pytestmark = pytest.mark.skipif(not postgres_disponivel(), reason=MOTIVO_SEM_POSTGRES)


DDL = """
CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS gold;

CREATE TABLE api.ml_orders (
    id           integer GENERATED BY DEFAULT AS IDENTITY,  -- surrogate: a armadilha
    order_id     bigint NOT NULL,
    brand        varchar NOT NULL,
    status       varchar NOT NULL,
    total_amount numeric,
    date_created timestamp NOT NULL
);

CREATE TABLE api.ml_order_line_items (
    order_id    bigint NOT NULL,
    line_number integer NOT NULL,
    quantity    smallint NOT NULL,
    unit_price  numeric,
    sale_fee    numeric
);

CREATE TABLE gold.ml_gestao_diaria (
    ref_date              date NOT NULL,
    brand                 varchar NOT NULL,
    gmv                   numeric,
    paid_orders           integer,
    total_units           integer,
    avg_ticket            numeric,
    unique_buyers         integer,
    new_buyers            integer,
    repeat_buyers         integer,
    repeat_buyer_rate_pct numeric,
    cancelled_orders      integer,
    cancel_rate_pct       numeric,
    delivered_shipments   integer,
    avg_delivery_days     numeric,
    seller_shipping_cost  numeric,
    shipping_pct_of_gmv   numeric,
    ad_spend              numeric,
    ad_revenue            numeric,
    ad_impressions        bigint,
    ad_clicks             bigint,
    roas                  numeric,
    acos_pct              numeric,
    ctr_pct               numeric,
    cpc                   numeric
);
"""

BRANDS = ("kokeshi", "lescent")


@pytest.fixture()
def banco():
    with cluster_descartavel() as url:
        eng = create_engine(url)
        with eng.begin() as conn:
            for stmt in filter(None, (s.strip() for s in DDL.split(";"))):
                conn.execute(text(stmt))
        yield eng
        eng.dispose()


def _gold(conn, ref_date, brand, gmv, paid_orders=10):
    conn.execute(
        text(
            "INSERT INTO gold.ml_gestao_diaria (ref_date, brand, gmv, paid_orders) "
            "VALUES (:d, :b, :g, :p)"
        ),
        {"d": ref_date, "b": brand, "g": gmv, "p": paid_orders},
    )


def _pedido(conn, order_id, brand, status, total, criado, itens):
    """`itens` = lista de (line_number, quantity, unit_price, sale_fee)."""
    conn.execute(
        text(
            "INSERT INTO api.ml_orders (order_id, brand, status, total_amount, date_created) "
            "VALUES (:o, :b, :s, :t, :c)"
        ),
        {"o": order_id, "b": brand, "s": status, "t": total, "c": criado},
    )
    for line_number, qty, price, fee in itens:
        conn.execute(
            text(
                "INSERT INTO api.ml_order_line_items "
                "(order_id, line_number, quantity, unit_price, sale_fee) "
                "VALUES (:o, :l, :q, :p, :f)"
            ),
            {"o": order_id, "l": line_number, "q": qty, "p": price, "f": fee},
        )


def _rodar(banco, date_from="2026-07-01", date_to="2026-07-31", brands=BRANDS):
    with banco.connect() as conn:
        rows = conn.execute(
            text(ml_connector.QUERY),
            {"brands": brands, "date_from": date_from, "date_to": date_to},
        ).mappings().all()
    return [dict(r) for r in rows]


def _por_chave(rows):
    return {(str(r["date"]), r["brand"]): r for r in rows}


# ---------------------------------------------------------------------------
# A chave do join
# ---------------------------------------------------------------------------

def test_join_por_order_id_encontra_a_comissao(banco):
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 1000)
        # order_id deliberadamente distante de `id` (que será 1)
        _pedido(conn, 2000012265767110, "kokeshi", "paid", 1000,
                "2026-07-10 14:00:00", [(1, 1, 1000, 170)])

    rows = _rodar(banco)
    assert len(rows) == 1
    assert float(rows[0]["marketplace_fee"]) == 170.0
    assert rows[0]["fee_orders"] == 1


def test_contraprova_join_pelo_surrogate_devolve_zero_em_silencio(banco):
    """A armadilha, executada.

    Trocar `o.order_id` por `o.id` não levanta erro: os dois são inteiros. A
    consulta simplesmente devolve NULL de comissão para todos os dias, e uma
    carga assim gravaria NULL por toda parte parecendo ter funcionado.
    """
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 1000)
        _pedido(conn, 2000012265767110, "kokeshi", "paid", 1000,
                "2026-07-10 14:00:00", [(1, 1, 1000, 170)])

    sql_errado = ml_connector.QUERY.replace("li.order_id = o.order_id", "li.order_id = o.id")
    with banco.connect() as conn:
        rows = conn.execute(
            text(sql_errado),
            {"brands": BRANDS, "date_from": "2026-07-01", "date_to": "2026-07-31"},
        ).mappings().all()

    assert len(rows) == 1, "a gold continua aparecendo — só a comissão some"
    assert rows[0]["marketplace_fee"] is None
    # E a consulta certa, no mesmo banco, acha o valor:
    assert float(_rodar(banco)[0]["marketplace_fee"]) == 170.0


# ---------------------------------------------------------------------------
# Quantidade e cardinalidade
# ---------------------------------------------------------------------------

def test_fee_e_multiplicado_pela_quantidade(banco):
    """`sale_fee` é por unidade: 3 unidades a 11,00 são 33,00 de comissão."""
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 300)
        _pedido(conn, 900001, "kokeshi", "paid", 300,
                "2026-07-10 10:00:00", [(1, 3, 100, 11)])

    assert float(_rodar(banco)[0]["marketplace_fee"]) == 33.0


def test_multiplos_itens_no_mesmo_pedido_somam_sem_duplicar_o_pedido(banco):
    """Join 1:N: a comissão soma os itens, mas `fee_orders` conta o pedido uma
    vez só. Se `fee_orders` contasse linhas, viraria 2 e qualquer razão
    calculada sobre ele ficaria pela metade."""
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 500)
        _pedido(conn, 900002, "kokeshi", "paid", 500, "2026-07-10 10:00:00",
                [(1, 1, 300, 50), (2, 2, 100, 15)])

    row = _rodar(banco)[0]
    assert float(row["marketplace_fee"]) == 50 + 30   # 50*1 + 15*2
    assert row["fee_orders"] == 1


def test_gold_nao_sofre_fan_out_quando_o_pedido_tem_varios_itens(banco):
    """O CTE agrega ANTES do join. Sem isso, a linha da gold se multiplicaria
    pelo número de itens e o GMV seria contado várias vezes."""
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 500)
        _pedido(conn, 900003, "kokeshi", "paid", 500, "2026-07-10 10:00:00",
                [(1, 1, 100, 10), (2, 1, 100, 10), (3, 1, 300, 30)])

    rows = _rodar(banco)
    assert len(rows) == 1
    assert float(rows[0]["gmv"]) == 500.0


def test_pedido_duplicado_na_fonte_soma_duas_vezes_e_isso_e_visivel(banco):
    """Contrato honesto: a consulta NÃO deduplica pedido.

    A fonte tem `order_id` único hoje — medido: 566.512 linhas para 566.512
    pares `(order_id, line_number)` distintos. Se isso deixar de valer, a
    comissão infla, e `fee_orders` é o que denuncia: ele conta DISTINCT, então
    a razão `marketplace_fee / fee_orders` sai fora de escala.
    """
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 1000)
        _pedido(conn, 900004, "kokeshi", "paid", 1000, "2026-07-10 10:00:00",
                [(1, 1, 1000, 170)])
        conn.execute(
            text(
                "INSERT INTO api.ml_order_line_items "
                "(order_id, line_number, quantity, unit_price, sale_fee) "
                "VALUES (900004, 1, 1, 1000, 170)"
            )
        )

    row = _rodar(banco)[0]
    assert float(row["marketplace_fee"]) == 340.0
    assert row["fee_orders"] == 1, "DISTINCT expõe a duplicata em vez de escondê-la"


# ---------------------------------------------------------------------------
# População elegível
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("status", ["cancelled", "partially_refunded", "payment_required"])
def test_status_inelegivel_nao_entra_na_comissao(banco, status):
    """Cancelado e parcialmente reembolsado estão fora do GMV da gold; manter
    a comissão deles inflaria o numerador contra um denominador que não os tem."""
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 1000)
        _pedido(conn, 900005, "kokeshi", status, 1000,
                "2026-07-10 10:00:00", [(1, 1, 1000, 170)])

    assert _rodar(banco)[0]["marketplace_fee"] is None


def test_pago_e_cancelado_no_mesmo_dia_soma_so_o_pago(banco):
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 1000)
        _pedido(conn, 900006, "kokeshi", "paid", 1000,
                "2026-07-10 10:00:00", [(1, 1, 1000, 170)])
        _pedido(conn, 900007, "kokeshi", "cancelled", 500,
                "2026-07-10 11:00:00", [(1, 1, 500, 85)])

    row = _rodar(banco)[0]
    assert float(row["marketplace_fee"]) == 170.0
    assert row["fee_orders"] == 1


def test_marca_fora_do_escopo_nao_entra(banco):
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 1000)
        _pedido(conn, 900008, "kokeshi", "paid", 1000,
                "2026-07-10 10:00:00", [(1, 1, 1000, 170)])
        _pedido(conn, 900009, "azbuy", "paid", 9999,
                "2026-07-10 10:00:00", [(1, 1, 9999, 999)])

    assert float(_rodar(banco)[0]["marketplace_fee"]) == 170.0


def test_dia_sem_pedido_pago_devolve_null_e_preserva_a_linha_da_gold(banco):
    """O LEFT JOIN é o que garante que a fato não perde o dia."""
    with banco.begin() as conn:
        _gold(conn, "2026-07-11", "kokeshi", 0, paid_orders=0)

    rows = _rodar(banco)
    assert len(rows) == 1
    assert rows[0]["marketplace_fee"] is None
    assert rows[0]["fee_orders"] is None


# ---------------------------------------------------------------------------
# Fronteira de dia e de janela
# ---------------------------------------------------------------------------

def test_pedido_no_ultimo_instante_do_dia_final_entra_na_janela(banco):
    """`date_created` é timestamp. Com `<= :date_to`, 23:59:59 do último dia
    ficaria de fora e a comissão daquele dia sairia truncada."""
    with banco.begin() as conn:
        _gold(conn, "2026-07-31", "kokeshi", 1000)
        _pedido(conn, 900010, "kokeshi", "paid", 1000,
                "2026-07-31 23:59:59", [(1, 1, 1000, 170)])

    rows = _rodar(banco, date_from="2026-07-01", date_to="2026-07-31")
    assert float(rows[0]["marketplace_fee"]) == 170.0


def test_pedido_do_primeiro_instante_do_dia_seguinte_fica_fora(banco):
    with banco.begin() as conn:
        _gold(conn, "2026-07-31", "kokeshi", 1000)
        _pedido(conn, 900011, "kokeshi", "paid", 1000,
                "2026-08-01 00:00:00", [(1, 1, 1000, 170)])

    rows = _rodar(banco, date_from="2026-07-01", date_to="2026-07-31")
    assert rows[0]["marketplace_fee"] is None


def test_comissao_cai_no_dia_do_date_created_nao_no_dia_seguinte(banco):
    """Atribuição de competência: o pedido das 23:00 pertence ao seu próprio
    dia. Um deslocamento de fuso apareceria aqui como comissão no dia errado."""
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 1000)
        _gold(conn, "2026-07-11", "kokeshi", 2000)
        _pedido(conn, 900012, "kokeshi", "paid", 1000,
                "2026-07-10 23:00:00", [(1, 1, 1000, 170)])

    por_dia = _por_chave(_rodar(banco))
    assert float(por_dia[("2026-07-10", "kokeshi")]["marketplace_fee"]) == 170.0
    assert por_dia[("2026-07-11", "kokeshi")]["marketplace_fee"] is None


def test_comissao_nao_vaza_entre_marcas_no_mesmo_dia(banco):
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 1000)
        _gold(conn, "2026-07-10", "lescent", 500)
        _pedido(conn, 900013, "kokeshi", "paid", 1000,
                "2026-07-10 10:00:00", [(1, 1, 1000, 170)])
        _pedido(conn, 900014, "lescent", "paid", 500,
                "2026-07-10 12:00:00", [(1, 1, 500, 60)])

    por_dia = _por_chave(_rodar(banco))
    assert float(por_dia[("2026-07-10", "kokeshi")]["marketplace_fee"]) == 170.0
    assert float(por_dia[("2026-07-10", "lescent")]["marketplace_fee"]) == 60.0


def test_fronteira_de_mes_separa_a_comissao(banco):
    with banco.begin() as conn:
        _gold(conn, "2026-07-31", "kokeshi", 1000)
        _gold(conn, "2026-08-01", "kokeshi", 1000)
        _pedido(conn, 900015, "kokeshi", "paid", 1000,
                "2026-07-31 22:00:00", [(1, 1, 1000, 170)])
        _pedido(conn, 900016, "kokeshi", "paid", 1000,
                "2026-08-01 02:00:00", [(1, 1, 1000, 180)])

    por_dia = _por_chave(_rodar(banco, date_from="2026-07-01", date_to="2026-08-31"))
    assert float(por_dia[("2026-07-31", "kokeshi")]["marketplace_fee"]) == 170.0
    assert float(por_dia[("2026-08-01", "kokeshi")]["marketplace_fee"]) == 180.0


# ---------------------------------------------------------------------------
# Determinismo
# ---------------------------------------------------------------------------

def test_consulta_e_deterministica_entre_execucoes(banco):
    with banco.begin() as conn:
        _gold(conn, "2026-07-10", "kokeshi", 1000)
        _pedido(conn, 900017, "kokeshi", "paid", 1000,
                "2026-07-10 10:00:00", [(1, 2, 500, 85)])

    primeira = _rodar(banco)
    segunda = _rodar(banco)
    assert primeira == segunda
    assert float(primeira[0]["marketplace_fee"]) == 170.0
